### PR TITLE
Install from Github + Example update

### PR DESCRIPTION
**Pull request by pommedeterresautee**

### CODE REVIEW

**Comment by pommedeterresautee** [comment]
@wush978  I have made changes to comments in example code.
Please check I have correctly understood the purpose of each line.

Kind regards,
Michaël

**Comment by wush978** [comment]
Thanks!

I will review them tonight(Taipei Time).

**Comment by pommedeterresautee** [comment]
Does the Hashing function use a seed to be generated?
If yes, the seed of the example should be fixed to guaranty constant results.

**Comment by wush978** [comment]
I see some changes of generated files of Rcpp attributes but I do not see the corresponding changes of .cpp files. Did you modify these generated files by hand?

**Comment by pommedeterresautee** [comment]
No, I noticed these change after pushing, I think it happened during the compilation. I may have a different version of RCPP than you have.

**Comment by pommedeterresautee** [comment]
Have you deleted this comment : I prefer to use mapping2["PlantQn2:uptake"] here, do you?


??

**Comment by wush978** [comment]
Yes. Because I just read my local patches and notice that I might not need that comment.

**Comment by wush978** [comment]
I like your patch about README and the source of documentation, but I will manually remove the change of auto generated files.

Thanks for your update.

**Comment by pommedeterresautee** [comment]
FYI I have Rcpp 0.11.4, may be it s the point.

**Comment by wush978** [comment]
Sweet, mine is 0.11.3.5

Note that 0.11.5 will be on CRAN soon

**Comment by pommedeterresautee** [comment]
May be if you update the version you will get the change in Rcpp in attributes, therefore no need to change the source code by hand.

**Pull request merged**
