### PR TITLE
Add TF-IDF weights for hashing matrix + update doc + update RMarkdown

### PR DESCRIPTION
**Pull request by pommedeterresautee**
http://en.wikipedia.org/wiki/Tf%E2%80%93idf

Improve performance on linear model. Very used in NLP but useful on other dataset. On Rmarkdown sentiment analysis example, results are decreased for the 10 first loop, but tested on 200 rounds, gain of 1 absolute point in classification error rate on this example (compared to using existence type).

Cost in performance, even for large hash Matrix, is a few seconds of computation.

!!!!!!!!! ERROR IN REPORTING PERFORMANCE - SEE BELOW !!!!!!!!!!!

### CODE REVIEW

**Comment by pommedeterresautee** [comment]
Mmmhh  the check failed because of RMarkdown not present? Any idea why? Or what can I do to fix?

**Comment by wush978** [comment]
Hmm.. could you add the required packages to the Suggests field in DESCRIPTION?

I'll review it on the weekend. Thanks.

**Comment by pommedeterresautee** [comment]
So far:


```
==> roxygen2::roxygenize('.', roclets=c('rd', 'namespace'))

Documentation completed

==> R CMD build FeatureHashing

* checking for file ‘FeatureHashing/DESCRIPTION’ ... OK
* preparing ‘FeatureHashing’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘FeatureHashing_0.9.1.tar.gz’

==> R CMD check --as-cran FeatureHashing_0.9.1.tar.gz

* using log directory ‘/home/geantvert/workspace/FeatureHashing.Rcheck’
* using R version 3.2.0 (2015-04-16)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using option ‘--as-cran’
* checking for file ‘FeatureHashing/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘FeatureHashing’ version ‘0.9.1’
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Wush Wu <wush978@gmail.com>’

Suggests or Enhances not in mainstream repositories:
  xgboost

The Date field is over a month old.
* checking package namespace information ... OK
* checking package dependencies ... NOTE
  No repository set, so cyclic dependency check skipped
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘FeatureHashing’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking compiled code ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘test-as-dgCMatrix.R’
  Running ‘test-empty_array.R’
  Running ‘test-hash.mapping.R’
  Running ‘test-hashing.R’
  Running ‘test-interpret.tag.R’
  Running ‘test-memcheck.R’
  Running ‘test-product.R’
  Running ‘test-signed.hash.R’
  Running ‘test-split.R’
  Running ‘test-subsetting.R’
  Running ‘test-transpose.R’ OK

* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
   ‘FeatureHashing.Rmd’ using ‘UTF-8’ ... OK
   ‘SentimentAnalysis.Rmd’ using ‘UTF-8’ ... OK
 OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
! LaTeX Error: File `inconsolata.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

! Emergency stop.
<read *> 
         
l.276 ^^M
         
!  ==> Fatal error occurred, no output PDF file produced!
* checking PDF version of manual without hyperrefs or index ... OK
* DONE
Status: 1 WARNING, 2 NOTEs
See
  ‘/home/geantvert/workspace/FeatureHashing.Rcheck/00check.log’
for details.


R CMD check succeeded
```

**Comment by wush978** [comment]
Dear @pommedeterresautee ,

I would like to postpone the reviewing due to the following two issues: #74 and #75 . 

Sorry about that.
Wush

**Comment by pommedeterresautee** [comment]
No problem I tried myself to fix the pandoc issue without success...

**Comment by wush978** [comment]
I am trying to install newest pandoc via haskell in .travis.yml ... hope that works.

**Comment by wush978** [comment]
Dear @pommedeterresautee ,

Could you manually merge the master branch? I have fixed the pandoc issue.

**Comment by pommedeterresautee** [comment]
Done.
BTW I made a mistake in reporting the improvement with TF-IDF on linear model. I got 11.4 in 10 rounds only (vs 12.1 using existence). In 20 rounds the score is optimal with 11.0 in TF-IDF which is good I think.

Next improvement is adding ngram :-)

**Comment by wush978** [comment]
Thanks!

**Pull request merged**
